In [1]:
import pandas as pd
df = pd.read_csv("COVID-19 Cases.csv")
print(df.shape)
df.head()

(106704, 10)

,Date,Country_Region,Province_State,Case_Type,Cases,Difference,Prep_Flow_Runtime,Latest_Date,Lat,Long
0,3/11/2020,US,Arizona,Recovered,0,0,3/20/2020 7:43:39 AM,3/19/2020,32.0575,-111.6661
1,3/11/2020,US,Arizona,Deaths,0,0,3/20/2020 7:43:39 AM,3/19/2020,32.0575,-111.6661
2,3/11/2020,US,Arizona,Confirmed,0,0,3/20/2020 7:43:39 AM,3/19/2020,32.0575,-111.6661
3,3/11/2020,US,Arizona,Active,0,0,3/20/2020 7:43:39 AM,3/19/2020,32.0575,-111.6661
4,2/15/2020,US,Arizona,Recovered,0,0,3/20/2020 7:43:39 AM,3/19/2020,32.8162,-111.2845

In [6]:
a = df[df.Country_Region == "Pakistan"][["Date", "Cases"]]
a = a[a.Cases != 0]
a.shape

(59, 2)

In [8]:
a

            Date  Cases
64704  3/19/2020     13
64705  3/19/2020      2
64706  3/19/2020    454
64707  3/19/2020    439
66470  2/27/2020      2
66471  2/27/2020      2
67420  3/18/2020      2
67422  3/18/2020    299
67423  3/18/2020    297
68446   3/2/2020      4
68447   3/2/2020      4
71954   3/5/2020      5
71955   3/5/2020      5
72484  3/17/2020      2
72486  3/17/2020    236
72487  3/17/2020    234
72746   3/4/2020      5
72747   3/4/2020      5
72852  3/10/2020      1
72854  3/10/2020     16
72855  3/10/2020     15
73866  2/28/2020      2
73867  2/28/2020      2
75752  3/12/2020      2
75754  3/12/2020     20
75755  3/12/2020     18
78268  3/16/2020      2
78270  3/16/2020    136
78271  3/16/2020    134
78974   3/7/2020      6
78975   3/7/2020      6
81908   3/8/2020      1
81910   3/8/2020      6
81911   3/8/2020      5
81912  3/11/2020      2
81914  3/11/2020     19
81915  3/11/2020     17
82136  3/14/2020      2
82138  3/14/2020     31
82139  3/14/2020     29
83408   3/9/2020      1
83410   3/9/2020      6
83411   3/9/2020      5
84630   3/1/2020      4
84631   3/1/2020      4
84834   3/3/2020      5
84835   3/3/2020      5
88930  2/29/2020      4
88931  2/29/2020      4
89892  3/15/2020      2
89894  3/15/2020     53
89895  3/15/2020     51
90616  3/13/2020      2
90618  3/13/2020     28
90619  3/13/2020     26
92402   3/6/2020      6
92403   3/6/2020      6
92934  2/26/2020      2
92935  2/26/2020      2